/* =============================================
   MIROMA AI HUB — Admin license data
   ============================================= */

const ADMIN_USERS = [
  // All-agency admins (super admins). `homeAgency` only controls which agency's
  // Admin Access list they appear under in the dashboard — it does NOT limit
  // access (access:'all' = full cross-agency). Defaults to miroma-group when unset.
  { email: 'aiteam@miroma.com',              name: 'AI Team',        access: 'all', homeAgency: 'ai-team' },
  { email: 'vishal.manjrekar@miroma.com',    name: 'Vishal',         access: 'all', homeAgency: 'ai-team' },
  { email: 'tess.mckean@miroma.com',         name: 'Tess',           access: 'all', homeAgency: 'ai-team' },
  { email: 'ben.pilgrim@miroma.com',         name: 'Ben',            access: 'all', homeAgency: 'ai-team' },
  { email: 'thomas.maycliffe@miroma.com',    name: 'Tom',            access: 'all', homeAgency: 'ai-team' },
  { email: 'vix.ross@miroma.com',            name: 'Vix',            access: 'all', homeAgency: 'ai-team' },
  { email: 'paul.summers@miroma.com',        name: 'Paul',           access: 'all' },
  { email: 'craig.lennon@miroma.com',        name: 'Craig Lennon',   access: 'all' },
  // Finance admins — licences and group spend view only, all agencies
  { email: 'ramiah.fletcher-thomas@miroma.com', name: 'Ramiah Fletcher-Thomas', access: 'finance' },
  { email: 'amber.mcintyre@miroma.com',         name: 'Amber McIntyre',         access: 'finance' },
  { email: 'francis.bonsu@miroma.com',          name: 'Francis Bonsu',          access: 'finance' },
  { email: 'adrian.talbot@miroma.com',          name: 'Adrian Talbot',          access: 'finance' },
  // Attentive
  { email: 'ben@attentive.media',            name: 'Ben Alpren',     access: 'agency', agency: 'attentive' },
  // Buzz16
  { email: 'joe.bennett@buzz16.uk',          name: 'Joe Bennett',    access: 'agency', agency: 'buzz16' },
  { email: 'scott@buzz16.uk',               name: 'Scott Melvin',   access: 'agency', agency: 'buzz16' },
  { email: 'duncan.east@buzz16.uk',          name: 'Duncan East',    access: 'agency', agency: 'buzz16' },
  // Dewynters
  { email: 'm.diamandi@dewynters.com',       name: 'Mike',           access: 'agency', agency: 'dewynters' },
  { email: 'n.cannock@dewynters.com',        name: 'Nicolle',        access: 'agency', agency: 'dewynters' },
  { email: 'a.williams@dewynters.com',       name: 'Alice',          access: 'agency', agency: 'dewynters' },
  { email: 'a.ewart@dewynters.com',          name: 'Anne',           access: 'agency', agency: 'dewynters' },
  { email: 'j.charrington@dewynters.com',    name: 'James Charrington', access: 'agency', agency: 'dewynters' },
  { email: 's.shimell@dewynters.com',        name: 'Simon Shimell',  access: 'agency', agency: 'dewynters' },
  // Fold7
  { email: 'james@fold7.com',               name: 'James Joice',    access: 'agency', agency: 'fold7' },
  { email: 'ryan@fold7.com',                name: 'Ryan Newey',     access: 'agency', agency: 'fold7' },
  { email: 'derek.morgans@fold7.com',        name: 'Derek Morgans',  access: 'agency', agency: 'fold7' },
  // Maker Lab
  { email: 'james@wearemakerlab.com',        name: 'James',          access: 'agency', agency: 'makerlab' },
  { email: 'matt@wearemakerlab.com',         name: 'Matt Shoult',    access: 'agency', agency: 'makerlab' },
  // MFN
  { email: 'richs@miromafounders.com',       name: 'Richard Stanton', access: 'agency', agency: 'mfn' },
  { email: 'jeevans@miromafounders.com',     name: 'Jeevan',         access: 'agency', agency: 'mfn' },
  // Multiple
  { email: 'mark@themultipleagency.com',     name: 'Mark',           access: 'agency', agency: 'multiple' },
  { email: 'rebecca@themultipleagency.com',  name: 'Rebecca',        access: 'agency', agency: 'multiple' },
  { email: 'adam@themultipleagency.com',     name: 'Adam',           access: 'agency', agency: 'multiple' },
  // MX UK
  { email: 'susie@mxlocation.co',           name: 'Susie',          access: 'agency', agency: 'mxuk' },
  // MX US
  { email: 'arran@mxlocation.co',           name: 'Arran',          access: 'agency', agency: 'mxus' },
  // Raven
  { email: 'yasmin@weareravenagency.com',    name: 'Yasmin Eady',    access: 'agency', agency: 'raven' },
  { email: 'sophie@weareravenagency.com',    name: 'Sophie Jewes',   access: 'agency', agency: 'raven' },
  // Sold Out
  { email: 'a.francis@soldout.co.uk',        name: 'Adrian',         access: 'agency', agency: 'soldout' },
  { email: 'jim@soldout.co.uk',              name: 'Jim',            access: 'agency', agency: 'soldout' },
  { email: 'luke@soldout.co.uk',             name: 'Luke',           access: 'agency', agency: 'soldout' },
  { email: 'freddie@soldout.co.uk',          name: 'Freddie',        access: 'agency', agency: 'soldout' },
  // Spot Co
  { email: 'cgoff@spotnyc.com',              name: 'Callie',         access: 'agency', agency: 'spotco' },
  { email: 'krathbun@spotnyc.com',           name: 'Kiki',           access: 'agency', agency: 'spotco' },
  { email: 'lschermerhorn@spotnyc.com',      name: 'Louis',          access: 'agency', agency: 'spotco' },
  { email: 'ssosnowski@spotnyc.com',         name: 'Stephen Sosnowski', access: 'agency', agency: 'spotco' },
  // Story House
  { email: 'david.bloom@storyhousepr.co.uk', name: 'David Bloom',    access: 'agency', agency: 'storyhouse' },
  // Twelve AM
  { email: 'oj@twelveam.com',               name: 'OJ',             access: 'agency', agency: 'twelveam' },
];

// Derived for backwards-compatible email lookups
const ADMIN_EMAILS = ADMIN_USERS.map(u => u.email);

// Primary contact for each agency — receives onboarding/offboarding emails
const AGENCY_CONTACTS = {
  attentive:      { email: 'ben@attentive.media',              name: 'Ben Alpren' },
  buzz16:         { email: 'joe.bennett@buzz16.uk',            name: 'Joe Bennett' },
  dewynters:      { email: 'm.diamandi@dewynters.com',         name: 'Mike Diamandi' },
  fold7:          { email: 'james@fold7.com',                  name: 'James Joice' },
  makerlab:       { email: 'james@wearemakerlab.com',          name: 'James Tugman' },
  mfn:            { email: 'richs@miromafounders.com',         name: 'Richard Stanton' },
  'miroma-group': { email: 'aiteam@miroma.com',                name: 'AI Team' },
  'ai-team':      { email: 'aiteam@miroma.com',                name: 'AI Team' },
  multiple:       { email: 'mark@themultipleagency.com',       name: 'Mark Keisner' },
  mxuk:           { email: 'susie@mxlocation.co',              name: 'Susie' },
  mxus:           { email: 'arran@mxlocation.co',              name: 'Arran Javed' },
  raven:          { email: 'yasmin@weareravenagency.com',      name: 'Yasmin Eady' },
  soldout:        { email: 'a.francis@soldout.co.uk',          name: 'Adrian Francis' },
  spotco:         { email: 'cgoff@spotnyc.com',                name: 'Callie Goff' },
  storyhouse:     { email: 'david.bloom@storyhousepr.co.uk',   name: 'David Bloom' },
  twelveam:       { email: 'oj@twelveam.com',                  name: 'OJ' },
};

const LICENSE_DATA = {
  agencies: [
    {
      // AI Team is a standalone agency. Its members' tool licences were moved
      // here out of Miroma Holdings (split per member, seats = headcount).
      key: 'ai-team',
      name: 'AI Team',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'AI Team',          email: 'aiteam@miroma.com',           team: 'AI Team org' },
            { name: 'Ben Pilgrim',      email: 'ben.pilgrim@miroma.com',      team: 'AI Team org' },
            { name: 'Thomas Maycliffe', email: 'thomas.maycliffe@miroma.com', team: 'AI Team org' },
            { name: 'Vix Ross',         email: 'vix.ross@miroma.com',         team: 'AI Team org' },
            { name: 'Tess McKean',      email: 'tess.mckean@miroma.com',      team: 'AI Team org' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 3,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 405,
          annualTotal: 4860,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Tess McKean',      email: 'tess.mckean@miroma.com',      team: 'AI Team', joinedAt: 'January 2025' },
            { name: 'Thomas Maycliffe', email: 'Thomas.Maycliffe@miroma.com', team: 'AI Team', joinedAt: 'January 2025' },
            { name: 'Ben Pilgrim',      email: 'Ben.Pilgrim@miroma.com',      team: 'AI Team', joinedAt: 'January 2025' },
          ],
        },
        {
          name: 'Springboards',
          seats: 2,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 300,
          annualTotal: 3600,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'Thomas Maycliffe', email: 'Thomas.maycliffe@miroma.com', team: '' },
            { name: 'Ben Pilgrim',      email: 'ben.pilgrim@miroma.com',      team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 6,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 85.5,
          annualTotal: 1026,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Thomas Maycliffe', email: 'thomas.maycliffe@miroma.com', team: 'Business' },
            { name: 'Vix Ross',         email: 'vix.ross@miroma.com',         team: 'Business' },
            { name: 'Ben Pilgrim',      email: 'ben.pilgrim@miroma.com',      team: 'Business' },
            { name: 'Tess McKean',      email: 'tess.mckean@miroma.com',      team: 'Business' },
            { name: 'Rohit Naidu',      email: 'rohit.naidu@miroma.com',      team: 'Business' },
            { name: 'Takshit Mathur',   email: 'takshit.mathur@miroma.com',   team: 'Business' },
          ],
        },
        {
          name: 'Descript',
          seats: 1,
          costPerSeat: 0,
          currency: '£',
          monthlyTotal: 0,
          annualTotal: 0,
          renewal: 'TBC',
          status: 'active',
          holders: [
            { name: 'AI Team', email: 'aiteam@miroma.com', team: '' },
          ],
        },
      ],
    },
    {
      key: 'spotco',
      name: 'Spot Co',
      tools: [
        {
          name: 'LTX Studio',
          seats: 12,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 1620,
          annualTotal: 19440,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Nicky Lindeman',   email: 'nlindeman@spotnyc.com',   team: 'Design',           joinedAt: 'January 2025' },
            { name: 'Matt Iacovelli',   email: 'miacovelli@spotnyc.com',  team: 'Design',           joinedAt: 'January 2025' },
            { name: 'Michelle Dimuzio', email: 'mdimuzio@spotnyc.com',    team: 'Design',           joinedAt: 'January 2025' },
            { name: 'Rex Bonomelli',    email: 'rbonomelli@spotnyc.com',  team: 'Design',           joinedAt: 'January 2025' },
            { name: 'Ryan Bloomquist',  email: 'rbloomquist@spotnyc.com', team: 'Copy',             joinedAt: 'January 2025' },
            { name: 'Julie Boor',       email: 'jboor@spotnyc.com',       team: 'New Business',     joinedAt: 'January 2025' },
            { name: 'Ren Julius Reyes', email: 'rjreyes@spotnyc.com',     team: 'Ad Design',        joinedAt: 'January 2025' },
            { name: 'Thomas Coppola',   email: 'tcoppola@spotnyc.com',    team: 'Production',       joinedAt: 'January 2025' },
            { name: 'Sean Maymon',      email: 'smaymon@spotnyc.com',     team: 'Production',       joinedAt: 'January 2025' },
            { name: 'Grayson Craddock', email: 'gcraddock@spotnyc.com',   team: 'Ad Design',        joinedAt: 'January 2025' },
            { name: 'Frank Gargiulo',   email: 'fgargiulo@spotnyc.com',   team: 'Design',           joinedAt: 'January 2025' },
            { name: 'Callie Goff',      email: 'cgoff@spotnyc.com',       team: 'Managing Director', joinedAt: 'January 2025' },
          ],
        },
        {
          name: 'Claude',
          seats: 17,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 272,
          annualTotal: 3264,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'AI Team',             email: 'aiteam@spotnyc.com',        team: 'Primary owner' },
            { name: 'Louis Schermerhorn', email: 'lschermerhorn@spotnyc.com', team: 'Owner' },
            { name: 'Andrew Lowy',         email: 'alowy@spotnyc.com',         team: '' },
            { name: 'Anne Gordon',         email: 'agordon@spotnyc.com',       team: '' },
            { name: 'Chris Scherer',       email: 'cscherer@spotnyc.com',      team: '' },
            { name: 'Emily Mauser',        email: 'emauser@spotnyc.com',       team: '' },
            { name: 'Gráinne Kelly',       email: 'gkelly@spotnyc.com',        team: '' },
            { name: 'Grayson Craddock',    email: 'gcraddock@spotnyc.com',     team: '' },
            { name: 'Jake Windoloski',     email: 'jwindoloski@spotnyc.com',   team: '' },
            { name: 'Julie Boor',          email: 'jboor@spotnyc.com',         team: '' },
            { name: 'Kim Suzzan',          email: 'ksuzzan@spotnyc.com',       team: '' },
            { name: 'Maris Smith',         email: 'msmith@spotnyc.com',        team: '' },
            { name: 'Noah Fried',          email: 'nfried@spotnyc.com',        team: '' },
            { name: 'Rebekah Moran',       email: 'rmoran@spotnyc.com',        team: '' },
            { name: 'Ren Julius Reyes',    email: 'rjreyes@spotnyc.com',       team: '' },
            { name: 'Ryan Bloomquist',     email: 'rbloomquist@spotnyc.com',   team: '' },
            { name: 'Sahiti Rudra',        email: 'srudra@spotnyc.com',        team: '' },
          ],
        },
        {
          name: 'Descript',
          seats: 1,
          costPerSeat: 0,
          currency: '£',
          monthlyTotal: 0,
          annualTotal: 0,
          renewal: 'TBC',
          status: 'active',
          holders: [
            { name: 'Grainne Kelly', email: 'gkelly@spotnyc.com', team: '' },
          ],
        },
        {
          name: 'Springboards',
          seats: 13,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 1950,
          annualTotal: 23400,
          renewal: 'July 2026 — not renewing',
          status: 'expiring',
          holders: [
            { name: 'Grainne Kelly',      email: 'gkelly@spotnyc.com',        team: '' },
            { name: 'Ren Julius Reyes',   email: 'rjreyes@spotnyc.com',       team: '' },
            { name: 'Louis Schermerhorn', email: 'lschermerhorn@spotnyc.com', team: '' },
            { name: 'Kiki Rathbun',       email: 'krathbun@spotnyc.com',      team: '' },
            { name: 'Ryan Bloomquist',    email: 'rbloomquist@spotnyc.com',   team: '' },
            { name: 'Chris Scherer',      email: 'cscherer@spotnyc.com',      team: '' },
            { name: 'Callie Goff',        email: 'cgoff@spotnyc.com',         team: '' },
            { name: 'Rex Bonomelli',      email: 'rbonomelli@spotnyc.com',    team: '' },
            { name: 'Anne Gordon',        email: 'agordon@spotnyc.com',       team: '' },
            { name: 'Grayson Craddock',   email: 'gcraddock@spotnyc.com',     team: '' },
            { name: 'Carly Consalvo',     email: 'cconsalvo@spotnyc.com',     team: '' },
            { name: 'Kiersten McAdoo',    email: 'kmcadoo@spotnyc.com',       team: '' },
            { name: 'Ian Joseph Avila',   email: 'iavila@spotnyc.com',        team: '' },
          ],
        },
      ],
    },
    {
      key: 'multiple',
      name: 'Multiple',
      tools: [
        {
          name: 'LTX Studio',
          seats: 3,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 405,
          annualTotal: 4860,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Luca Di Maio', email: 'lucad@themultipleagency.com',    team: 'Video Editor',  joinedAt: 'March 2025' },
            { name: 'Joe T',        email: 'joet@themultipleagency.com',     team: 'Art Director',  joinedAt: 'March 2025' },
            { name: 'Freddie O',    email: 'FreddieO@themultipleagency.com', team: '',              joinedAt: 'March 2025' },
          ],
        },
        {
          name: 'Springboards',
          seats: 6,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 900,
          annualTotal: 10800,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'Joe T',          email: 'joet@themultipleagency.com',    team: '' },
            { name: 'Mark Keisner',   email: 'mark@themultipleagency.com',    team: '' },
            { name: 'Matt Farnworth', email: 'mattf@themultipleagency.com',   team: '', joinedAt: 'May 2025' },
            { name: 'Olu Balogun',    email: 'olu@themultipleagency.com',     team: '' },
            { name: 'Rebecca Winch',  email: 'rebecca@themultipleagency.com', team: '' },
            { name: 'Adam Bullock',   email: 'adam@themultipleagency.com',    team: '' },
          ],
        },
        {
          name: 'Claude',
          seats: 10,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 160,
          annualTotal: 1920,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Mark Keisner',        email: 'mark@themultipleagency.com',     team: '' },
            { name: 'AI Team',             email: 'aiteam@themultipleagency.com',   team: '' },
            { name: 'Dana',                email: 'danas@themultipleagency.com',    team: '' },
            { name: 'Evie',                email: 'eviep@themultipleagency.com',    team: '' },
            { name: 'Joe',                 email: 'joet@themultipleagency.com',     team: '' },
            { name: 'Matt Farnworth',      email: 'mattf@themultipleagency.com',    team: '', joinedAt: 'May 2025' },
            { name: 'Matthew W',           email: 'mattheww@themultipleagency.com', team: '' },
            { name: 'Olivia Hetherington', email: 'oliviah@themultipleagency.com',  team: '' },
            { name: 'Olu',                 email: 'olu@themultipleagency.com',      team: '' },
            { name: 'Rebecca Winch',       email: 'rebecca@themultipleagency.com',  team: '' },
          ],
        },
      ],
    },
    {
      key: 'miroma-group',
      name: 'Miroma Holdings Ltd',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Paul Summers',       email: 'paul.summers@miroma.com',       team: 'Miroma Holdings org' },
            { name: 'AI Team',            email: 'aiteam@miroma.com',             team: 'Miroma Holdings org' },
            { name: 'Aidan Shephard',     email: 'aidan.shephard@miroma.com',     team: 'Miroma Holdings org' },
            { name: 'Jean-Philippe Amos', email: 'Jean-Philippe.Amos@miroma.com', team: 'Miroma Holdings org' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 2,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 270,
          annualTotal: 3240,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Aidan Shephard',   email: 'aidan.shephard@miroma.com',   team: 'Creative Design Lead', joinedAt: 'January 2025' },
            { name: 'Katie Robinson',   email: 'Katie.Robinson@miroma.com',   team: 'Marketing' },
          ],
        },
        {
          name: 'Springboards',
          seats: 2,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 300,
          annualTotal: 3600,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'Aidan Shephard',   email: 'aidan.shephard@miroma.com',   team: '' },
            { name: 'Katie Robinson',   email: 'Katie.Robinson@miroma.com',   team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 1,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 14.25,
          annualTotal: 171,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Katie Robinson',   email: 'katie.robinson@miroma.com',   team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'miroma-outcomes',
      name: 'Miroma Outcomes',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'TBC',
          status: 'active',
          holders: [
            { name: 'Mark Hilton', email: 'mark.hilton@miroma.com', team: '' },
            { name: 'AI Team',     email: 'aiteam@miroma.com',      team: '' },
            { name: 'Paul Mann',   email: 'paul.mann@miroma.com',   team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 1,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 14.25,
          annualTotal: 171,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Paul Mann', email: 'paul.mann@miroma.com', team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'attentive',
      name: 'Attentive',
      tools: [
        {
          name: 'Claude',
          seats: 8,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 128,
          annualTotal: 1536,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Ben Alpren',          email: 'ben@attentive.media',      team: '' },
            { name: 'AI Team',             email: 'aiteam@attentive.media',   team: '' },
            { name: 'Rebecca Fox-Wilsher', email: 'rebecca@attentive.media',  team: '' },
            { name: 'Claudia Kirkby',      email: 'claudia@attentive.media',  team: '' },
            { name: 'Eren Blake',          email: 'eren@attentive.media',     team: '' },
            { name: 'Fariha Islam',        email: 'fariha@attentive.media',   team: 'Rebilled to Miroma SET' },
            { name: 'Sammuel Bello',       email: 'sam@attentive.media',      team: '' },
            { name: 'Sarah Anthony',       email: 'sarah@attentive.media',    team: '' },
          ],
        },
      ],
    },
    {
      key: 'mxus',
      name: 'MX US',
      tools: [
        {
          name: 'Claude',
          seats: 6,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 96,
          annualTotal: 1152,
          renewal: 'July 2027',
          status: 'active',
          holders: [
            { name: 'MHL central', email: 'aiteam@miroma.com',      team: 'Primary owner' },
            { name: 'Arran Javed', email: 'arran@mxlocation.co',    team: 'Owner' },
            { name: 'Clay',        email: 'clay@mxlocation.co',     team: '' },
            { name: 'Jasmyn',      email: 'jasmyn@mxlocation.co',   team: '' },
            { name: 'Sam',         email: 'sam@mxlocation.co',      team: '' },
            { name: 'Kristin',     email: 'kristin@mxlocation.co',  team: 'Pending' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 1,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 135,
          annualTotal: 1620,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Arran Javed', email: 'arran@mxlocation.co', team: 'Global Lead' },
          ],
        },
      ],
    },
    {
      key: 'dewynters',
      name: 'Dewynters',
      tools: [
        {
          name: 'Claude',
          seats: 80,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 1280,
          annualTotal: 15360,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Michael Diamandi', email: 'm.diamandi@dewynters.com', team: 'Primary owner' },
            { name: 'MHL central', email: 'aiteam@miroma.com', team: 'Owner' },
            { name: 'Nicolle Cannock', email: 'n.cannock@dewynters.com', team: 'Admin' },
            { name: 'Aashni Sadanandan', email: 'a.sadanandan@dewynters.com', team: '' },
            { name: 'Adam Fulrath', email: 'a.fulrath@dewynters.com', team: '' },
            { name: 'Adam Kirkham', email: 'a.kirkham@dewynters.com', team: '' },
            { name: 'Ailsa Mackenzie', email: 'a.hoke@dewynters.com', team: '' },
            { name: 'Alex Slattery', email: 'a.slattery@dewynters.com', team: '' },
            { name: 'Alex Cameron', email: 'a.cameron@dewynters.com', team: '' },
            { name: 'Alice Williams', email: 'A.Williams@dewynters.com', team: '' },
            { name: 'Amber Trott', email: 'A.Trott@dewynters.com', team: '' },
            { name: 'Amber Conran', email: 'a.conran@dewynters.com', team: '' },
            { name: 'Anne Ewart', email: 'A.Ewart@dewynters.com', team: '' },
            { name: 'Benji Hurring', email: 'B.Hurring@dewynters.com', team: '' },
            { name: 'Charlee Dobson', email: 'c.dobson@dewynters.com', team: '' },
            { name: 'Fahim Ahmed', email: 'f.ahmed@dewynters.com', team: '' },
            { name: 'Fi Joseph', email: 'F.Joseph@dewynters.com', team: '' },
            { name: 'Georgi Bessey', email: 'g.bessey@dewynters.com', team: '' },
            { name: 'Hedley Lipang', email: 'h.lipang@miromaset.com', team: '' },
            { name: 'Henry Brown', email: 'H.Brown@dewynters.com', team: '' },
            { name: 'Imogen O\'Leary', email: 'i.oleary@dewynters.com', team: '' },
            { name: 'Liz Wilde', email: 'E.Wilde@dewynters.com', team: '' },
            { name: 'Lucy MacMillan', email: 'l.macmillan@dewynters.com', team: '' },
            { name: 'Max Wilson', email: 'm.wilson@dewynters.com', team: '' },
            { name: 'Michael Havard-Bilton', email: 'm.havard-bilton@dewynters.com', team: '' },
            { name: 'Michelle Penston', email: 'M.Penston@dewynters.com', team: '' },
            { name: 'Monica Yell', email: 'm.yell@dewynters.com', team: '' },
            { name: 'Naomi Finn', email: 'n.finn@dewynters.com', team: '' },
            { name: 'Nate Anantharajah', email: 'N.Anantharajah@dewynters.com', team: '' },
            { name: 'Sergio Cicalo', email: 's.cicalo@dewynters.com', team: '' },
            { name: 'Simon Richards', email: 'S.Richards@dewynters.com', team: '' },
            { name: 'Simon Shimell', email: 's.shimell@dewynters.com', team: '' },
            { name: 'Tom Jewett', email: 't.jewett@dewynters.com', team: '' },
            { name: 'Tom Roberts', email: 't.roberts@dewynters.com', team: '' },
            { name: 'Wendell Harrison', email: 'w.harrison@dewynters.com', team: '' },
            { name: 'A. Ali', email: 'A.Ali@dewynters.com', team: 'Pending invite' },
            { name: 'A. Blecua', email: 'a.blecua@dewynters.com', team: 'Pending invite' },
            { name: 'A. Clason', email: 'A.Clason@dewynters.com', team: 'Pending invite' },
            { name: 'A. Dann', email: 'A.Dann@dewynters.com', team: 'Pending invite' },
            { name: 'A. Landon', email: 'a.landon@dewynters.com', team: 'Pending invite' },
            { name: 'B. Jefferis', email: 'b.jefferis@dewynters.com', team: 'Pending invite' },
            { name: 'C. Green', email: 'c.green@dewynters.com', team: 'Pending invite' },
            { name: 'C Wentworth', email: 'c.wentworth@dewynters.com', team: 'Pending invite' },
            { name: 'D. Hill', email: 'D.Hill@dewynters.com', team: 'Pending invite' },
            { name: 'E. Hayward', email: 'e.hayward@dewynters.com', team: 'Pending invite' },
            { name: 'E. Mitchell', email: 'e.mitchell@dewynters.com', team: 'Pending invite' },
            { name: 'F. Carpenter', email: 'F.Carpenter@dewynters.com', team: 'Pending invite' },
            { name: 'G. Boyle', email: 'g.boyle@dewynters.com', team: 'Pending invite' },
            { name: 'G. Ghoussein', email: 'G.Ghoussein@dewynters.com', team: 'Pending invite' },
            { name: 'H. Collins', email: 'H.Collins@dewynters.com', team: 'Pending invite' },
            { name: 'I. Curtis', email: 'I.Curtis@dewynters.com', team: 'Pending invite' },
            { name: 'I. Riskute', email: 'I.Riskute@dewynters.com', team: 'Pending invite' },
            { name: 'I. Stevens', email: 'I.Stevens@dewynters.com', team: 'Pending invite' },
            { name: 'J. Davenport-Braes', email: 'J.Davenport-Braes@dewynters.com', team: 'Pending invite' },
            { name: 'J. Nicholls', email: 'j.nicholls@dewynters.com', team: 'Pending invite' },
            { name: 'K. Eastham', email: 'K.Eastham@dewynters.com', team: 'Pending invite' },
            { name: 'Kirsty Taylor', email: 'kirsty.taylor@dewynters.com', team: 'Pending invite' },
            { name: 'L. Burrell', email: 'L.Burrell@dewynters.com', team: 'Pending invite' },
            { name: 'L. Cattermole', email: 'L.Cattermole@dewynters.com', team: 'Pending invite' },
            { name: 'L. Thorpe', email: 'l.thorpe@dewynters.com', team: 'Pending invite' },
            { name: 'L. Watts', email: 'L.Watts@dewynters.com', team: 'Pending invite' },
            { name: 'M. Crockett', email: 'm.crockett@dewynters.com', team: 'Pending invite' },
            { name: 'M. Joseph', email: 'M.Joseph@dewynters.com', team: 'Pending invite' },
            { name: 'M. Marsden', email: 'm.marsden@dewynters.com', team: 'Pending invite' },
            { name: 'N. Bartle', email: 'n.bartle@dewynters.com', team: 'Pending invite' },
            { name: 'N. Roig', email: 'N.Roig@dewynters.com', team: 'Pending invite' },
            { name: 'N. ScottHowe', email: 'N.ScottHowe@dewynters.com', team: 'Pending invite' },
            { name: 'P Goodman', email: 'p.goodman@dewynters.com', team: 'Pending invite' },
            { name: 'P. Roberts', email: 'p.roberts@dewynters.com', team: 'Pending invite' },
            { name: 'P. Safavi', email: 'p.safavi@dewynters.com', team: 'Pending invite' },
            { name: 'R. Cook', email: 'R.Cook@dewynters.com', team: 'Pending invite' },
            { name: 'R. Jenkins', email: 'r.jenkins@dewynters.com', team: 'Pending invite' },
            { name: 'Richard McDermott', email: 'r.mcdermott@dewynters.com', team: 'Pending invite' },
            { name: 'R. Penn', email: 'r.penn@dewynters.com', team: 'Pending invite' },
            { name: 'S. Awadalla', email: 'S.Awadalla@dewynters.com', team: 'Pending invite' },
            { name: 'S. Netherton', email: 'S.Netherton@dewynters.com', team: 'Pending invite' },
            { name: 'S. Overington', email: 's.overington@dewynters.com', team: 'Pending invite' },
            { name: 'S. Webb', email: 's.webb@dewynters.com', team: 'Pending invite' },
            { name: 'T. Greenaway', email: 't.greenaway@dewynters.com', team: 'Pending invite' },
            { name: 'T. Pullen', email: 'T.Pullen@dewynters.com', team: 'Pending invite' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 3,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 405,
          annualTotal: 4860,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Adam Fulrath',      email: 'a.fulrath@dewynters.com',   team: 'Director of Creative Services', joinedAt: 'January 2025' },
            { name: 'Naomi Finn',        email: 'n.finn@dewynters.com',      team: 'Senior Designer',               joinedAt: 'January 2025' },
            { name: 'Richard McDermott', email: 'r.mcdermott@dewynters.com', team: '', joinedAt: 'February 2025' },
          ],
        },
        {
          name: 'Springboards',
          seats: 1,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 150,
          annualTotal: 1800,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'H Wilson', email: 'h.wilson@dewynters.com', team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 81,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 1154.25,
          annualTotal: 13851,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'A Williams',          email: 'a.williams@dewynters.com',          team: 'Business' },
            { name: 'M Diamandi',          email: 'm.diamandi@dewynters.com',          team: 'Business' },
            { name: 'C Green',             email: 'c.green@dewynters.com',             team: 'Business' },
            { name: 'T Jewett',            email: 't.jewett@dewynters.com',            team: 'Business' },
            { name: 'I O\'Leary',          email: 'i.oleary@dewynters.com',            team: 'Business' },
            { name: 'N Cannock',           email: 'n.cannock@dewynters.com',           team: 'Business' },
            { name: 'C Dobson',            email: 'c.dobson@dewynters.com',            team: 'Business' },
            { name: 'S Gee',               email: 's.gee@dewynters.com',               team: 'Business' },
            { name: 'A Fisher',            email: 'a.fisher@dewynters.com',            team: 'Business' },
            { name: 'Fireflies Admin',     email: 'firefliesadmin@dewynters.com',      team: 'Business' },
            { name: 'I Riskute',           email: 'i.riskute@dewynters.com',           team: 'Business' },
            { name: 'Fireflies Test 2',    email: 'firefliestest2@dewynters.com',      team: 'Business' },
            { name: 'Fireflies Toolkit',   email: 'firefliestoolkit@dewynters.com',    team: 'Business' },
            { name: 'P Safavi',            email: 'p.safavi@dewynters.com',            team: 'Business' },
            { name: 'M Penston',           email: 'm.penston@dewynters.com',           team: 'Business' },
            { name: 'K Eastham',           email: 'k.eastham@dewynters.com',           team: 'Business' },
            { name: 'L MacMillan',         email: 'l.macmillan@dewynters.com',         team: 'Business' },
            { name: 'T Lodge',             email: 't.lodge@dewynters.com',             team: 'Business' },
            { name: 'A Hoke',              email: 'a.hoke@dewynters.com',              team: 'Business' },
            { name: 'L Bailey',            email: 'l.bailey@dewynters.com',            team: 'Business' },
            { name: 'L Thorpe',            email: 'l.thorpe@dewynters.com',            team: 'Business' },
            { name: 'J Charrington',       email: 'j.charrington@dewynters.com',       team: 'Business' },
            { name: 'B Jefferis',          email: 'b.jefferis@dewynters.com',          team: 'Business' },
            { name: 'C Wentworth',         email: 'c.wentworth@dewynters.com',         team: 'Business' },
            { name: 'S Webb',              email: 's.webb@dewynters.com',              team: 'Business' },
            { name: 'R Penn',              email: 'r.penn@dewynters.com',              team: 'Business' },
            { name: 'N Finn',              email: 'n.finn@dewynters.com',              team: 'Business' },
            { name: 'M Crockett',          email: 'm.crockett@dewynters.com',          team: 'Business' },
            { name: 'T Roberts',           email: 't.roberts@dewynters.com',           team: 'Business' },
            { name: 'E Nugent',            email: 'e.nugent@dewynters.com',            team: 'Business' },
            { name: 'D Hill',              email: 'd.hill@dewynters.com',              team: 'Business' },
            { name: 'A Blecua',            email: 'a.blecua@dewynters.com',            team: 'Business' },
            { name: 'M Marsden',           email: 'm.marsden@dewynters.com',           team: 'Business' },
            { name: 'P Roberts',           email: 'p.roberts@dewynters.com',           team: 'Business' },
            { name: 'N Bartle',            email: 'n.bartle@dewynters.com',            team: 'Business' },
            { name: 'S Cumbley',           email: 's.cumbley@dewynters.com',           team: 'Business' },
            { name: 'I Curtis',            email: 'i.curtis@dewynters.com',            team: 'Business' },
            { name: 'M Havard-Bilton',     email: 'm.havard-bilton@dewynters.com',     team: 'Business' },
            { name: 'R Phear',             email: 'r.phear@dewynters.com',             team: 'Business' },
            { name: 'A Fulrath',           email: 'a.fulrath@dewynters.com',           team: 'Business' },
            { name: 'R McDermott',         email: 'r.mcdermott@dewynters.com',         team: 'Business' },
            { name: 'I Stevens',           email: 'i.stevens@dewynters.com',           team: 'Business' },
            { name: 'N Roig',              email: 'n.roig@dewynters.com',              team: 'Business' },
            { name: 'E Jenks',             email: 'e.jenks@dewynters.com',             team: 'Business' },
            { name: 'P Goodman',           email: 'p.goodman@dewynters.com',           team: 'Business' },
            { name: 'S Partridge',         email: 's.partridge@dewynters.com',         team: 'Business' },
            { name: 'R Jenkins',           email: 'r.jenkins@dewynters.com',           team: 'Business' },
            { name: 'H Wilson',            email: 'h.wilson@dewynters.com',            team: 'Business' },
            { name: 'J Applegate',         email: 'j.applegate@dewynters.com',         team: 'Business' },
            { name: 'B Hurring',           email: 'b.hurring@dewynters.com',           team: 'Business' },
            { name: 'A Conran',            email: 'a.conran@dewynters.com',            team: 'Business' },
            { name: 'S Netherton',         email: 's.netherton@dewynters.com',         team: 'Business' },
            { name: 'L Paulraj',           email: 'l.paulraj@dewynters.com',           team: 'Business' },
            { name: 'J Davenport-Braes',   email: 'j.davenport-braes@dewynters.com',   team: 'Business' },
            { name: 'E Hayward',           email: 'e.hayward@dewynters.com',           team: 'Business' },
            { name: 'K Rogers',            email: 'k.rogers@dewynters.com',            team: 'Business' },
            { name: 'A Trott',             email: 'a.trott@dewynters.com',             team: 'Business' },
            { name: 'A Cameron',           email: 'a.cameron@dewynters.com',           team: 'Business' },
            { name: 'E Mitchell',          email: 'e.mitchell@dewynters.com',          team: 'Business' },
            { name: 'A Ewart',             email: 'a.ewart@dewynters.com',             team: 'Business' },
            { name: 'H Brown',             email: 'h.brown@dewynters.com',             team: 'Business' },
            { name: 'R Cook',              email: 'r.cook@dewynters.com',              team: 'Business' },
            { name: 'T Olowu',             email: 't.olowu@dewynters.com',             team: 'Business' },
            { name: 'T Wye',               email: 't.wye@dewynters.com',               team: 'Business' },
            { name: 'M Byrne',             email: 'm.byrne@dewynters.com',             team: 'Business' },
            { name: 'G Bessey',            email: 'g.bessey@dewynters.com',            team: 'Business' },
            { name: 'S Cicalo',            email: 's.cicalo@dewynters.com',            team: 'Business' },
            { name: 'L Burrell',           email: 'l.burrell@dewynters.com',           team: 'Business' },
            { name: 'M Joseph',            email: 'm.joseph@dewynters.com',            team: 'Business' },
            { name: 'S Awadalla',          email: 's.awadalla@dewynters.com',          team: 'Business' },
            { name: 'A Slattery',          email: 'a.slattery@dewynters.com',          team: 'Business' },
            { name: 'L Cattermole',        email: 'l.cattermole@dewynters.com',        team: 'Business' },
            { name: 'A Dann',              email: 'a.dann@dewynters.com',              team: 'Business' },
            { name: 'M Wilson',            email: 'm.wilson@dewynters.com',            team: 'Business' },
            { name: 'C Levy',              email: 'c.levy@dewynters.com',              team: 'Business' },
            { name: 'M Yell',              email: 'm.yell@dewynters.com',              team: 'Business' },
            { name: 'V Zachariadi',        email: 'v.zachariadi@dewynters.com',        team: 'Business' },
            { name: 'T Greenaway',         email: 't.greenaway@dewynters.com',         team: 'Business' },
            { name: 'F Joseph',            email: 'f.joseph@dewynters.com',            team: 'Business' },
            { name: 'B Philip-Bayliss',    email: 'b.philip-bayliss@dewynters.com',    team: 'Business' },
            { name: 'S Overington',        email: 's.overington@dewynters.com',        team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'makerlab',
      name: 'Maker Lab',
      tools: [
        {
          name: 'Claude',
          seats: 16,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 256,
          annualTotal: 3072,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'James Tugman',  email: 'james@wearemakerlab.com',     team: '' },
            { name: 'Ethan Chia',    email: 'ethan@wearemakerlab.com',     team: '' },
            { name: 'Apoorv Sharma', email: 'apoorv@wearemakerlab.com',    team: '' },
            { name: 'Aryati',        email: 'iam@wearemakerlab.com',       team: '' },
            { name: 'Chloe',         email: 'chloe@wearemakerlab.com',     team: '' },
            { name: 'John',          email: 'john@wearemakerlab.com',      team: '' },
            { name: 'Joshua',        email: 'joshua@wearemakerlab.com',    team: '' },
            { name: 'Kam',           email: 'kam@wearemakerlab.com',       team: '' },
            { name: 'Matt Shoult',   email: 'matt@wearemakerlab.com',      team: '' },
            { name: 'Rashi',         email: 'rashi@wearemakerlab.com',     team: '' },
            { name: 'Rubi',          email: 'rubi@wearemakerlab.com',      team: '' },
            { name: 'Sheryl Goh',    email: 'sherylgoh@wearemakerlab.com', team: '' },
            { name: 'Yasmin',        email: 'yasmin@wearemakerlab.com',    team: '' },
            { name: 'Nadiya',        email: 'nadiya@wearemakerlab.com',    team: 'Pending invite' },
            { name: 'Reema',         email: 'reema@wearemakerlab.com',     team: 'Pending invite' },
            { name: 'Suyin',         email: 'suyin@wearemakerlab.com',     team: 'Pending invite' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 4,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 540,
          annualTotal: 6480,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Liyana',       email: 'liyana@wearemakerlab.com',   team: 'Art Director — Singapore Tourism Board',  joinedAt: 'January 2025' },
            { name: 'Dani',         email: 'danielle@wearemakerlab.com', team: 'Content Creator — Singapore Tourism Board', joinedAt: 'January 2025' },
            { name: 'Aola',         email: 'aola@wearemakerlab.com',     team: 'Content Creator — Singapore Tourism Board', joinedAt: 'January 2025' },
            { name: 'James Tugman', email: 'james@wearemakerlab.com',    team: '' },
          ],
        },
        {
          name: 'Springboards',
          seats: 5,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 750,
          annualTotal: 9000,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'Nadiya',    email: 'nadiya@wearemakerlab.com',    team: '' },
            { name: 'John',      email: 'john@wearemakerlab.com',      team: '' },
            { name: 'Liyana',    email: 'liyana@wearemakerlab.com',    team: '' },
            { name: 'Sheryl Goh', email: 'sherylgoh@wearemakerlab.com', team: '' },
            { name: 'James',     email: 'james@wearemakerlab.com',     team: '' },
          ],
        },
      ],
    },
    {
      key: 'mxuk',
      name: 'MX UK',
      tools: [],
    },
    {
      key: 'buzz16',
      name: 'Buzz16',
      tools: [
        {
          name: 'Descript',
          seats: 3,
          costPerSeat: 0,
          currency: '£',
          monthlyTotal: 0,
          annualTotal: 0,
          renewal: 'TBC',
          status: 'active',
          holders: [
            { name: 'Harvey Gillett', email: 'harvey.gillett@buzz16.uk',  team: '' },
            { name: 'Alex O\'Neill',  email: 'Alex.ONeill@buzz16.uk',     team: '' },
            { name: 'TBC',            email: '',                           team: '' },
          ],
        },
      ],
    },
    {
      key: 'mfn',
      name: 'MFN',
      tools: [
        {
          name: 'Claude',
          seats: 13,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 208,
          annualTotal: 2496,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'MHL central',            email: 'aiteam@miroma.com',            team: 'Primary owner' },
            { name: 'Jeevan Singh',            email: 'jeevans@miromafounders.com',   team: 'Owner' },
            { name: 'Richard Stanton',         email: 'richs@miromafounders.com',     team: 'Admin' },
            { name: 'Abbie Hildebrand',        email: 'abbieh@miromafounders.com',    team: '' },
            { name: 'Abigail Morrish',         email: 'abim@miromafounders.com',      team: '' },
            { name: 'Alex Lamaro McCrindle',   email: 'alexlm@miromafounders.com',    team: '' },
            { name: 'Amy Pountain',            email: 'amyp@miromafounders.com',      team: '' },
            { name: 'Calum Hollington',        email: 'calumh@miromafounders.com',    team: '' },
            { name: 'Cameron D',               email: 'camerond@miromafounders.com',  team: '' },
            { name: 'Carlos Calero Fernandez', email: 'carloscf@miromafounders.com',  team: '' },
            { name: 'Chris Andrews',           email: 'chrisa@miromafounders.com',    team: '' },
            { name: 'Toby Strangewood',        email: 'tobys@miromafounders.com',     team: '' },
            { name: 'Jasmine Hunt',            email: 'JasmineH@miromafounders.com',  team: 'Pending invite' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 22,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 313.50,
          annualTotal: 3762,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Ali M',       email: 'alim@miromafounders.com',       team: 'Business' },
            { name: 'Chris A',     email: 'chrisa@miromafounders.com',     team: 'Business' },
            { name: 'Jeevan S',    email: 'jeevans@miromafounders.com',    team: 'Business' },
            { name: 'Richard S',   email: 'richs@miromafounders.com',      team: 'Business' },
            { name: 'Carlos CF',   email: 'carloscf@miromafounders.com',   team: 'Business' },
            { name: 'Toby S',      email: 'tobys@miromafounders.com',      team: 'Business' },
            { name: 'Georgia M',   email: 'georgiam@miromafounders.com',   team: 'Business' },
            { name: 'Amy P',       email: 'amyp@miromafounders.com',       team: 'Business' },
            { name: 'Lenka T',     email: 'lenkat@miromafounders.com',     team: 'Business' },
            { name: 'Adam W',      email: 'adamw@miromafounders.com',      team: 'Business' },
            { name: 'Tom H',       email: 'tomh@miromafounders.com',       team: 'Business' },
            { name: 'Joe D',       email: 'joed@miromafounders.com',       team: 'Business' },
            { name: 'Beatrice M',  email: 'beatricem@miromafounders.com',  team: 'Business' },
            { name: 'Joseph L',    email: 'josephl@miromafounders.com',    team: 'Business' },
            { name: 'Calum H',     email: 'calumh@miromafounders.com',     team: 'Business' },
            { name: 'Ted E',       email: 'tede@miromafounders.com',       team: 'Business' },
            { name: 'Renee GM',    email: 'reneegm@miromafounders.com',    team: 'Business' },
            { name: 'Jono W',      email: 'jonow@miromafounders.com',      team: 'Business' },
            { name: 'Alex LM',     email: 'alexlm@miromafounders.com',     team: 'Business' },
            { name: 'Abi M',       email: 'abim@miromafounders.com',       team: 'Business' },
            { name: 'Temitayo O',  email: 'temitayoo@miromafounders.com',  team: 'Business' },
            { name: 'Rich S',      email: 'richs@wakethebear.co.uk',       team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'soldout',
      name: 'Sold Out',
      tools: [
        {
          name: 'Claude',
          seats: 16,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 256,
          annualTotal: 3072,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Luke',           email: 'luke@soldout.co.uk',          team: '' },
            { name: 'AI Team',        email: 'aiteam@miroma.com',           team: '' },
            { name: 'Freddie',        email: 'freddie@soldout.co.uk',       team: '' },
            { name: 'Aaron',          email: 'aaron@soldout.co.uk',         team: '' },
            { name: 'Alessia',        email: 'alessia@soldout.co.uk',       team: '' },
            { name: 'Ellie',          email: 'eleanor@soldout.co.uk',       team: '' },
            { name: 'Fereshta',       email: 'fereshta@soldout.co.uk',      team: '' },
            { name: 'Hannah Edwards', email: 'hannah.edwards@soldout.co.uk', team: '' },
            { name: 'Hannah Dawson',  email: 'hannah.dawson@soldout.co.uk',  team: '' },
            { name: 'Harry',          email: 'harrison@soldout.co.uk',      team: '' },
            { name: 'Hayley',         email: 'hayley@soldout.co.uk',        team: '' },
            { name: 'Jake',           email: 'jake@soldout.co.uk',          team: '' },
            { name: 'Jim',            email: 'jim@soldout.co.uk',           team: '' },
            { name: 'Lydia',          email: 'lydia@soldout.co.uk',         team: '' },
            { name: 'Mert',           email: 'mert@soldout.co.uk',          team: '' },
            { name: 'Raj',            email: 'rajdeep@soldout.co.uk',       team: '' },
          ],
        },
      ],
    },
    {
      key: 'fold7',
      name: 'Fold7',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'AI Team',       email: 'aiteam@miroma.com',        team: '' },
            { name: 'Derek Morgans', email: 'derek.morgans@fold7.com',  team: '' },
          ],
        },
        {
          name: 'Springboards',
          seats: 1,
          costPerSeat: 150,
          currency: '£',
          monthlyTotal: 150,
          annualTotal: 1800,
          renewal: 'July 2026',
          status: 'active',
          holders: [
            { name: 'Hannah March', email: 'hannah.march@fold7.com', team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 23,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 327.75,
          annualTotal: 3933,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Derek Morgans',       email: 'derek.morgans@fold7.com',       team: 'Business' },
            { name: 'Ben Gibbons',         email: 'ben.gibbons@fold7.com',         team: 'Business' },
            { name: 'Lucy Arnold',         email: 'lucy.arnold@fold7.com',         team: 'Business' },
            { name: 'Charlotte Fitzpatrick', email: 'charlotte.fitzpatrick@fold7.com', team: 'Business' },
            { name: 'Lara Caspersonn',     email: 'lara.caspersonn@fold7.com',     team: 'Business' },
            { name: 'Jamie Herman',        email: 'jamie.herman@fold7.com',        team: 'Business' },
            { name: 'Hannah March',        email: 'hannah.march@fold7.com',        team: 'Business' },
            { name: 'Ciara Jenkins',       email: 'ciara.jenkins@fold7.com',       team: 'Business' },
            { name: 'Tom Munckton',        email: 'tom.munckton@fold7.com',        team: 'Business' },
            { name: 'James May',           email: 'james.may@fold7.com',           team: 'Business' },
            { name: 'Maggie Roberts',      email: 'maggie.roberts@fold7.com',      team: 'Business' },
            { name: 'James',              email: 'james@fold7.com',               team: 'Business' },
            { name: 'Michelle Hickey',     email: 'michelle.hickey@fold7.com',     team: 'Business' },
            { name: 'Dave Billing',        email: 'dave.billing@fold7.com',        team: 'Business' },
            { name: 'Lizzie Clayton',      email: 'lizzie.clayton@fold7.com',      team: 'Business' },
            { name: 'Toby Moore',          email: 'toby.moore@fold7.com',          team: 'Business' },
            { name: 'Hannah Burles',       email: 'hannah.burles@fold7.com',       team: 'Business' },
            { name: 'Sally-Ann Stucke',    email: 'sally-ann.stucke@fold7.com',    team: 'Business' },
            { name: 'Buster Stonham',      email: 'buster.stonham@fold7.com',      team: 'Business' },
            { name: 'Izy',                email: 'izy@fold7.com',                 team: 'Business' },
            { name: 'Stuart Lundy',        email: 'stuart.lundy@fold7.com',        team: 'Business' },
            { name: 'Alex Leach',          email: 'alex.leach@fold7.com',          team: 'Business' },
            { name: 'Meg Hugill',          email: 'meg.hugill@fold7.com',          team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'twelveam',
      name: 'Twelve AM',
      tools: [
        {
          name: 'Claude',
          seats: 7,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 112,
          annualTotal: 1344,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Sam Herbert',     email: 'sam@twelveam.com',    team: '' },
            { name: 'Thaïs Montjean', email: 'thais@twelveam.com',  team: '' },
            { name: 'Rianna Reed',     email: 'rianna@twelveam.com', team: '' },
            { name: 'Josh Harrison',   email: 'josh@twelveam.com',   team: '' },
            { name: 'Jacob Strugnell', email: 'jacob@twelveam.com',  team: '' },
            { name: 'OJ Deady',        email: 'oj@twelveam.com',     team: '' },
            { name: 'AI Team',         email: 'aiteam@miroma.com',   team: '' },
          ],
        },
        {
          name: 'LTX Studio',
          seats: 1,
          costPerSeat: 135,
          currency: '£',
          monthlyTotal: 135,
          annualTotal: 1620,
          renewal: 'January 2027',
          status: 'active',
          holders: [
            { name: 'Sam', email: 'sam@twelveam.com', team: '', joinedAt: 'April 2025' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 1,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 14.25,
          annualTotal: 171,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'OJ', email: 'oj@twelveam.com', team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'finance',
      name: 'Finance',
      tools: [
        {
          name: 'Claude',
          seats: 13,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 208,
          annualTotal: 2496,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Richard Hogg',           email: 'richard.hogg@miroma.com',           team: 'Primary owner' },
            { name: 'Adrian Talbot',          email: 'adrian.talbot@miroma.com',          team: 'Owner' },
            { name: 'MHL central',            email: 'aiteam@miroma.com',                 team: 'Owner' },
            { name: 'Ramiah Fletcher-Thomas', email: 'ramiah.fletcher-thomas@miroma.com', team: 'Owner' },
            { name: 'Alex Simpson',           email: 'alex.simpson@miroma.com',           team: '' },
            { name: 'Amber McIntyre',         email: 'amber.mcintyre@miroma.com',         team: '' },
            { name: 'Andrew Gwilt',           email: 'andrew.gwilt@miroma.com',           team: '' },
            { name: 'Andrey Paska',           email: 'andrey.paska@miroma.com',           team: '' },
            { name: 'Dave Buck',              email: 'dave.buck@miroma.com',              team: '' },
            { name: 'Francis Bonsu',          email: 'francis.bonsu@miroma.com',          team: '' },
            { name: 'Jamie Plunkett',         email: 'jamie.plunkett@miroma.com',         team: '' },
            { name: 'Lida Pracharova',        email: 'Lida.Pracharova@miroma.com',        team: '' },
            { name: 'Rebecca Gallagher',      email: 'rebecca.gallagher@miroma.com',      team: '' },
          ],
        },
        {
          name: 'Fireflies',
          seats: 2,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 28.5,
          annualTotal: 342,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Richard Hogg',  email: 'richard.hogg@miroma.com',  team: 'Business' },
            { name: 'Andrey Paska',  email: 'andrey.paska@miroma.com',  team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'legal',
      name: 'Legal',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'July 2027',
          status: 'active',
          holders: [
            { name: 'Janey Parker',     email: 'janey.parker@miroma.com',     team: 'Primary owner' },
            { name: 'MHL central',      email: 'aiteam@miroma.com',           team: 'Owner' },
            { name: 'Alexandra Cooper', email: 'alexandra.cooper@miroma.com', team: 'Pending' },
            { name: 'David Norman',     email: 'david.norman@miroma.com',     team: 'Pending' },
          ],
        },
      ],
    },
    {
      key: 'hr',
      name: 'HR',
      tools: [
        {
          name: 'Fireflies',
          seats: 3,
          costPerSeat: 14.25,
          currency: '£',
          monthlyTotal: 42.75,
          annualTotal: 513,
          renewal: 'Monthly rolling',
          status: 'active',
          holders: [
            { name: 'Tihana Muftic', email: 'tihana.muftic@miroma.com', team: 'Business' },
            { name: 'Lexi Lewis',    email: 'lexi.lewis@miroma.com',    team: 'Business' },
            { name: 'Bhavna Patel',  email: 'bhavna.patel@miroma.com',  team: 'Business' },
          ],
        },
      ],
    },
    {
      key: 'miroma-set',
      name: 'Miroma SET',
      tools: [
        {
          name: 'Claude',
          seats: 5,
          costPerSeat: 16,
          currency: '£',
          monthlyTotal: 80,
          annualTotal: 960,
          renewal: 'May 2027',
          status: 'active',
          holders: [
            { name: 'Simon Shimell',   email: 's.shimell@dewynters.com', team: '' },
            { name: 'Elizabeth Wilde', email: '',                         team: '' },
            { name: 'Hedley Li Pang', email: '',                         team: '' },
            { name: 'AI Team',         email: 'aiteam@miroma.com',       team: '' },
          ],
        },
      ],
    },
  ],
};
