// ── Group AI Progress dashboard renderer ────────────────────────────────
//
// window.renderGroupReport(container, data)
//
// Live, browser equivalent of the CEO one-pager
// (Miroma/ai-usage-reporting/Group Reports/<period>/onepager.template.html)
// — same sections, minus "Next steps" (hand-written editorial judgement
// each month, not derived data, so it deliberately isn't reproduced here).
//
// data shape: one /group_reports/{period} document, computed by
// scripts/usage/aggregate-group-report.mjs from the SAME per-agency
// Firestore docs the Usage Reports / Group Spend / AI Hub Engagement tabs
// already read — so the numbers here should always reconcile with those.
//
// Reuses window.levelFor() from js/claude-usage.js (this file MUST load
// after claude-usage.js in admin.html) so the Exploring/Adopting/Embedded/
// Leading thresholds live in exactly one place, not a second copy that can
// silently drift from the per-agency dashboards' own adoption hero card.

(function () {
  'use strict';

  function esc(v) {
    return String(v ?? '')
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  // Some headline values are genuinely non-numeric strings (e.g. Maker
  // Lab's Talent Tool reports "500+", not 500) — pass those through as-is
  // rather than mangling them through Number()/toLocaleString.
  function fmt(n) {
    if (typeof n === 'string' && !/^-?\d+(\.\d+)?$/.test(n.trim())) return n;
    return Math.round(Number(n) || 0).toLocaleString('en-GB');
  }
  function fmtWeek(w) {
    if (!w) return '—';
    var d = new Date(w + 'T00:00:00');
    return isNaN(d) ? w : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  }
  function hoursToDays(h) { return Math.round((Number(h) || 0) / 7.5); }

  var LEVEL_NAMES = ['Exploring', 'Adopting', 'Embedded', 'Leading'];
  // Worded in terms of LICENSED SEATS, not headcount — the stages are computed
  // from how the agency's Claude-licensed users behave, not its total staff.
  var LEVEL_BLURB = [
    'licensed, few seats active yet',
    'over half of licensed seats active',
    'all licensed seats active, with depth',
    'all licensed seats active, deep and sustained',
  ];

  // ── Header ──
  function buildHeader(data) {
    return '<div class="gr-head">' +
      '<div><div class="gr-eyebrow">Miroma Group · AI Team · Live group summary</div>' +
      '<h2 class="gr-h1">Agency AI Progress</h2></div>' +
      '<div class="gr-badge">Data to ' + esc(data.period) + '</div>' +
      '</div>';
  }

  // ── KPI cards ──
  // Tool usage + Hub engagement only. The AI-team-built automations
  // (Meta Ads, Talent Tool) live in their own "What we've built" section
  // lower down — they're a different kind of thing from group-wide tool
  // adoption, and grouping them separately reads more clearly.
  function buildKpiCards(data) {
    var c = (data.claude && data.claude.totals) || {};
    var l = (data.ltx && data.ltx.totals) || {};
    var reportingCount = (data.claude && data.claude.reportingAgencyKeys || []).length;
    var hub = data.hubEngagement || {};

    var cards = [
      {
        lbl: 'Claude conversations', val: fmt(c.conversations),
        sub: 'Across ' + reportingCount + ' teams on usage reporting — ' + fmt(c.active_users) + ' active users, ' + fmt(c.power_users) + ' power users',
      },
      {
        lbl: 'Claude projects', val: fmt(c.total_projects),
        sub: fmt(c.shared_projects) + ' shared, reusable team workflows — the step beyond one-off chats',
      },
      {
        lbl: 'LTX generations', val: fmt(l.generations),
        sub: 'Creative assets generated by ' + fmt(l.active_users) + ' active users across ' + ((data.ltx && data.ltx.reportingAgencyCount) || 0) + ' teams',
      },
      { lbl: 'AI Hub site visits', val: fmt(hub.totalSiteVisits), sub: 'Total visits recorded by the Hub' },
      { lbl: 'Ready-to-copy use cases', val: fmt(data.useCaseCount), sub: 'Live in the Hub’s use-case library' },
    ];

    return '<div class="gr-kpis">' + cards.map(function (k) {
      return '<div class="gr-kpi' + (k.hl ? ' gr-kpi--hl' : '') + '">' +
        '<div class="gr-kpi__lbl">' + esc(k.lbl) + '</div>' +
        '<div class="gr-kpi__val">' + k.val + '</div>' +
        '<div class="gr-kpi__sub">' + k.sub + '</div>' +
        '</div>';
    }).join('') + '</div>';
  }

  // ── Claude adoption trend (weekly, all reporting agencies summed) ──
  function buildTrendChart(data) {
    var weeks = (data.claude && data.claude.weeklyTrend) || [];
    if (!weeks.length) {
      return '<div class="gr-card gr-trend-card"><h3>Claude adoption trend</h3><div class="gr-csub">No weekly data in this period\'s snapshots yet.</div></div>';
    }
    var totalAgencies = (data.claude.reportingAgencyKeys || []).length;
    var maxC = Math.max.apply(null, weeks.map(function (w) { return w.conversations || 0; })) || 1;
    var bars = weeks.map(function (w) {
      var h = Math.max(3, Math.round((w.conversations / maxC) * 100));
      var partial = totalAgencies > 0 && w.agenciesReporting < totalAgencies;
      var title = fmtWeek(w.week) + ': ' + fmt(w.conversations) + ' conversations' +
        (partial ? ' (partial — ' + w.agenciesReporting + '/' + totalAgencies + ' agencies had data for this week)' : '');
      return '<div class="gr-trend__col" title="' + esc(title) + '">' +
        '<div class="gr-trend__bar' + (partial ? ' gr-trend__bar--partial' : '') + '" style="height:' + h + '%"></div>' +
        '<div class="gr-trend__lab">' + esc(fmtWeek(w.week)) + '</div>' +
        '</div>';
    }).join('');
    return '<div class="gr-card gr-trend-card"><h3>Claude adoption trend</h3>' +
      '<div class="gr-csub">Conversations per week, all reporting teams</div>' +
      '<div class="gr-trend">' + bars + '</div>' +
      '<div class="gr-chart-note">Hover a bar for the exact count — a lighter bar means not every agency’s export covered that week.</div>' +
      '</div>';
  }

  // ── What teams use Claude for ──
  function buildWorkflowBars(data) {
    var wfs = ((data.claude && data.claude.workflowTotals) || [])
      .filter(function (w) { return w.key !== 'misc'; })
      .slice(0, 10);
    if (!wfs.length) return '<div class="gr-card"><h3>What teams use Claude for</h3><div class="gr-csub">No workflow data yet.</div></div>';
    var max = wfs[0].conversations || 1;
    var rows = wfs.map(function (w) {
      var width = Math.round((w.conversations / max) * 100);
      return '<div class="gr-hbar"><div class="gr-hbar__top"><span>' + esc(w.label) + '</span><span>' + fmt(w.conversations) + '</span></div>' +
        '<div class="gr-hbar__track"><div class="gr-hbar__fill" style="width:' + width + '%"></div></div></div>';
    }).join('');
    return '<div class="gr-card"><h3>What teams use Claude for</h3><div class="gr-csub">Top workflows by conversations, all teams</div>' + rows + '</div>';
  }

  // ── What we've built — AI-team-built automations in production use ──
  // Each automation's snapshot has its own shape, so we lean on the common
  // fields the aggregator normalises (headlineValue/unit, sinceLabel, and
  // hoursSaved where the source provides it).
  function buildBuilds(data) {
    var autos = data.automations || [];
    if (!autos.length) return '';
    var cards = autos.map(function (a) {
      var agencyName = (a.raw && a.raw.agency) || a.agencyKey;
      var val = (a.headlineValue != null ? fmt(a.headlineValue) : '—') + (a.headlineUnit ? ' <small>' + esc(a.headlineUnit) + '</small>' : '');
      var meta = esc(agencyName) + (a.sinceLabel ? ', ' + esc(a.sinceLabel) : '');
      var saved = a.hoursSaved != null
        ? '~' + fmt(a.hoursSaved) + ' hrs saved' + (a.workingDays != null ? ' · ≈' + fmt(a.workingDays) + ' days' : '')
        : '';
      return '<div class="gr-build">' +
        '<div class="gr-build__name">' + esc(a.automationName) + '</div>' +
        '<div class="gr-build__val">' + val + '</div>' +
        '<div class="gr-build__meta">' + meta + '</div>' +
        (saved ? '<div class="gr-build__saved">' + saved + '</div>' : '') +
        '</div>';
    }).join('');
    return '<div class="gr-card"><h3>Custom automations in production</h3>' +
      '<div class="gr-csub">Bespoke tools built for individual agencies</div>' +
      '<div class="gr-builds">' + cards + '</div></div>';
  }

  // ── Licence matrix ──
  function buildLicenceMatrix(data) {
    var lic = data.licences || { matrix: [], toolTotals: {}, toolAgencyCounts: {}, grandTotal: 0 };
    var tools = Object.keys(lic.toolTotals).sort(function (a, b) { return lic.toolTotals[b] - lic.toolTotals[a]; });
    var rows = (lic.matrix || [])
      .slice()
      .sort(function (a, b) { return a.agencyName.localeCompare(b.agencyName); })
      .map(function (r) {
        var cells = tools.map(function (t) {
          var n = r.byTool[t];
          return '<td' + (n ? '' : ' class="gr-mtx__z"') + '>' + (n || '—') + '</td>';
        }).join('');
        return '<tr><td>' + esc(r.agencyName) + '</td>' + cells + '<td class="gr-mtx__tot">' + r.total + '</td></tr>';
      }).join('');
    var totalsRow = '<tr class="gr-mtx__totrow"><td>Total seats</td>' +
      tools.map(function (t) { return '<td>' + lic.toolTotals[t] + '</td>'; }).join('') +
      '<td>' + lic.grandTotal + '</td></tr>';
    var countRow = '<tr class="gr-mtx__agcount"><td>Agencies on each tool</td>' +
      tools.map(function (t) { return '<td>' + lic.toolAgencyCounts[t] + '</td>'; }).join('') +
      '<td></td></tr>';
    return '<div class="gr-card"><h3>Licences by tool and agency</h3>' +
      '<div class="gr-csub">Paid seats — from the AI Hub’s Group Spend data</div>' +
      '<table class="gr-mtx"><thead><tr><th>Agency</th>' +
      tools.map(function (t) { return '<th>' + esc(t) + '</th>'; }).join('') +
      '<th>Total</th></tr></thead><tbody>' + rows + totalsRow + countRow + '</tbody></table></div>';
  }

  // ── Adoption curve — recomputed live via window.levelFor(), one agency
  //    at a time, so this can never disagree with a per-agency dashboard's
  //    own adoption hero card. ──
  function buildAdoptionCurve(data) {
    var levelForFn = window.levelFor;
    var stages = [[], [], [], []];
    (data.claude && data.claude.perAgency || []).forEach(function (a) {
      var lvl = levelForFn ? levelForFn(a.summary, a.summary.power_users) : 1;
      stages[Math.min(Math.max(lvl, 1), 4) - 1].push(a.agencyName);
    });
    var reportingKeys = (data.claude && data.claude.reportingAgencyKeys) || [];
    // Agencies we deliberately DON'T gather Claude usage data for, on
    // data-security grounds. They still hold licences (so they appear in the
    // licence/spend views), but they're pulled out of the usage/adoption
    // sections and called out separately below — not lumped in with
    // "not yet measured", which implies they'll be added later. Keep this list
    // in sync with USAGE_EXCLUDED_AGENCIES in js/admin-panel.js.
    var USAGE_EXCLUDED_KEYS = ['hr', 'miroma-group', 'legal'];
    var allAgencies = data.allAgencies || [];
    var excludedNames = allAgencies
      .filter(function (a) { return USAGE_EXCLUDED_KEYS.indexOf(a.key) !== -1; })
      .map(function (a) { return a.name; });
    var notReporting = allAgencies
      .filter(function (a) { return reportingKeys.indexOf(a.key) === -1 && USAGE_EXCLUDED_KEYS.indexOf(a.key) === -1; })
      .map(function (a) { return a.name; });

    // Bar length = NUMBER of agencies at each stage, so the section reads as a
    // distribution (heavy early, tapering to a few leaders) rather than the old
    // progress-ladder, which misleadingly made "Leading" the longest bar.
    // Not-yet-reporting agencies are split out below — they're unmeasured, not
    // a measured stage.
    var maxCount = Math.max(1, stages[0].length, stages[1].length, stages[2].length, stages[3].length);

    var html = stages.map(function (names, i) {
      var count = names.length;
      var w = Math.round((count / maxCount) * 100);
      var whoText = count ? '<b>' + names.map(esc).join(', ') + '</b>' : 'No agency at this stage yet.';
      return '<div class="gr-stage"><div class="gr-stage__num">' + (i + 1) + '</div>' +
        '<div><div class="gr-stage__name">' + LEVEL_NAMES[i] + ' <span>— ' + LEVEL_BLURB[i] + '</span></div>' +
        '<div class="gr-stage__barrow">' +
          '<div class="gr-stage__track"><div class="gr-stage__fill" style="width:' + w + '%"></div></div>' +
          '<div class="gr-stage__count">' + count + '</div>' +
        '</div>' +
        '<div class="gr-stage__who">' + whoText + '</div></div></div>';
    }).join('');

    var note = notReporting.length
      ? '<div class="gr-stage__note"><b>Not yet in reporting (' + notReporting.length + '):</b> ' +
        notReporting.map(esc).join(', ') + ' — licensed, usage not yet measured.</div>'
      : '';
    var excludedNote = excludedNames.length
      ? '<div class="gr-stage__note"><b>Excluded from usage reporting (' + excludedNames.length + '):</b> ' +
        excludedNames.map(esc).join(', ') + ' — licensed, but Claude usage data is deliberately not collected for these teams on data-security grounds.</div>'
      : '';

    if (!levelForFn) {
      html = '<p class="admin-loading">window.levelFor is unavailable — js/claude-usage.js must load before js/group-report.js.</p>' + html;
    }

    return '<div class="gr-card"><h3>Where each agency is on the adoption curve</h3>' +
      '<div class="gr-csub">Number of agencies at each stage — computed live from this period’s Claude usage data</div>' + html + note + excludedNote + '</div>';
  }

  // ── Estimated time efficiencies ──
  function buildTimeEfficiencies(data) {
    var c = (data.claude && data.claude.totals) || {};
    var l = (data.ltx && data.ltx.totals) || {};
    var items = [{
      n: fmt(c.hoursLow) + '–' + fmt(c.hoursHigh) + ' <b>hrs</b>',
      days: '≈' + hoursToDays(c.hoursLow) + '–' + hoursToDays(c.hoursHigh) + ' days',
      l: 'Claude — theoretical, from workflow minute-bands agreed when mapping workflows with the agencies',
    }];
    (data.automations || []).forEach(function (a) {
      // Not every automation's source snapshot has a precomputed timeSaved
      // block (see aggregate-group-report.mjs) — skip rather than guess.
      if (a.hoursSaved == null) return;
      var agencyName = (a.raw && a.raw.agency) || a.agencyKey;
      items.push({
        n: '~' + fmt(a.hoursSaved) + ' <b>hrs</b>',
        days: '≈' + (a.workingDays != null ? fmt(a.workingDays) : hoursToDays(a.hoursSaved)) + ' days',
        l: esc(a.automationName) + ' — ' + esc(agencyName) + (a.sinceLabel ? ', ' + esc(a.sinceLabel) : ''),
      });
    });
    if (l.hoursSaved) {
      items.push({
        n: '~' + fmt(l.hoursSaved) + ' <b>hrs</b>',
        days: '≈' + hoursToDays(l.hoursSaved) + ' days',
        l: 'LTX — indicative per-generation estimate, the least validated; treat as directional',
      });
    }
    var cols = items.map(function (e) {
      return '<div class="gr-eff__e"><div class="gr-eff__n">' + e.n + '</div><div class="gr-eff__days">' + e.days + '</div><div class="gr-eff__l">' + e.l + '</div></div>';
    }).join('');
    return '<div class="gr-card"><h3>Turning time saved into value</h3>' +
      '<div class="gr-csub">Modelled hours saved to date — and how we’re validating them into real bottom-line value</div>' +
      '<div class="gr-eff">' + cols + '</div>' +
      '<div class="gr-callout"><b>Validating the value.</b> These are modelled estimates, not yet P&amp;L figures. Each month we sit with each agency’s leadership to track how these hypothetical savings are converting into real bottom-line value — documented monthly for group-leadership visibility.</div>' +
      '</div>';
  }

  // ── Next steps — hand-authored editorial content, published verbatim
  //    by aggregate-group-report.mjs (see NEXT_STEPS there); not derived
  //    from any usage metric, so there's nothing to compute here. ──
  function buildNextSteps(data) {
    var steps = data.nextSteps || [];
    if (!steps.length) return '<div class="gr-card"><h3>Next steps — moving agencies up the curve</h3><div class="gr-csub">None set for this period.</div></div>';
    var items = steps.map(function (s) {
      return '<li><b>' + esc(s.title) + '</b> ' + esc(s.body) + '</li>';
    }).join('');
    return '<div class="gr-card"><h3>Next steps — moving agencies up the curve</h3><ul class="gr-ns">' + items + '</ul></div>';
  }

  // ── Footer ──
  function buildFooter(data) {
    return '<div class="gr-foot"><b>Scope.</b> Live rollup for period ' + esc(data.period) + ', computed by ' +
      'scripts/usage/aggregate-group-report.mjs from the same per-agency Firestore data shown on Usage Reports, ' +
      'Group Spend and AI Hub Engagement — figures here should always reconcile with those tabs. ' +
      'Hours are estimates — see “Read with care” above.</div>';
  }

  function renderGroupReport(container, data) {
    if (!container) return;
    if (!data) {
      container.innerHTML = '<p class="admin-loading">No group report has been published yet. Run scripts/usage/aggregate-group-report.mjs for the current period.</p>';
      return;
    }
    container.innerHTML =
      '<div class="gr-root">' +
      buildHeader(data) +
      buildKpiCards(data) +
      '<div class="gr-charts">' + buildTrendChart(data) + buildWorkflowBars(data) + '</div>' +
      '<div class="gr-mid">' +
      buildLicenceMatrix(data) +
      buildAdoptionCurve(data) +
      '</div>' +
      buildBuilds(data) +
      '<div class="gr-bot">' +
      buildTimeEfficiencies(data) +
      buildNextSteps(data) +
      '</div>' +
      buildFooter(data) +
      '</div>';
  }

  window.renderGroupReport = renderGroupReport;
})();
